name: packsquash

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          config-path: packsquash.toml
          output-path: Frontierparkspack.zip

      - name: Upload pack to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          source: "Fr
