name: Optimize resource pack

on: 
  [push, workflow_dispatch]

jobs:
  packsquash:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for PackSquash

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          options_file: packsquash.toml  # Your PackSquash config file
          path: Frontierparkspack        # Folder where assets/, pack.mcmeta, etc. are

      - name: Upload optimized pack to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: optimized-pack
          path: pack.zip  # Output file from PackSquash

      - name: Upload via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USER }}
          password: ${{ secrets.SCP_PASS }}
          source: "pack.zip"
          target: "/path/on/server"
