name: packsquash

on:
  push:
    branches:
      - main # or your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          config-path: packsquash.toml
          output-path: pack.zip

      - name: Upload pack to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # or use password: ${{ secrets.PASSWORD }}
          source: "pack.zip"
          target: "/var/www/html/resourcepacks/" # Change to your web folder

      - name: Update server.properties
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
          "sed -i 's|^resource-pack=.*|resource-pack=${{ secrets.RESOURCE_PACK_URL }}|g' /path/to/server/server.properties"
